#!/usr/bin/env bash

shim_domainset() {
  file="$1"
  egrep -v '^#|7h1s_rul35et_i5_mad3_by_5ukk4w|this_ruleset_is_made_by_sukkaw|th1s_rule5et_1s_m4d3_by_5ukk4w' $file |\
    cut -d'#' -f1 |\
    sed \
      -e 's/ //g' \
      -e 's/^\./*./g'
}

shim_ruleset() {
  file="$1"
  grep -Pi '^(DOMAIN,|DOMAIN-SUFFIX,)(?!7h1s_rul35et_i5_mad3_by_5ukk4w|this_ruleset_is_made_by_sukkaw|th1s_rule5et_1s_m4d3_by_5ukk4w)' $file |\
    cut -d'#' -f1 |\
    sed \
      -e 's/ //g' \
      -e 's/DOMAIN,/-./g' \
      -e 's/DOMAIN-SUFFIX,//g'
}

shim_dnsmasq() {
  file="$1"
  sed 's#server=/##g;s#/114.114.114.114##g' "$file"
}

simplify() {
  $utils_path/simplify_domainset.py $@
}
