#!/usr/bin/env bash

workdir="$GITHUB_WORKSPACE"
file="$workdir/bili.yml"

curl -L https://github.com/SunsetMkt/anti-ip-attribution/raw/refs/heads/main/rules/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9.yaml -o $file

pip install yq
yq '.config.rules' $file | grep '"' | cut -d'"' -f2 > $workdir/bili.rules || exit 1

grep 'REJECT' $workdir/bili.rules | awk -F',' '{ print $1 "," $2; }' > $workdir/build/bili_reject.txt
grep 'DIRECT' $workdir/bili.rules | awk -F',' '{ print $1 "," $2; }' > $workdir/build/bili_direct.txt
grep -vE 'REJECT|DIRECT' $workdir/bili.rules | awk -F',' '{ print $1 "," $2; }' > $workdir/build/bili_proxy.txt
echo "DOMAIN-KEYWORD,d1--ov-" >> $workdir/build/bili_proxy.txt
